### ISSUE TITLE
[enhancement] Integrate files to make your repository accessible for HomeAssistant?

### ISSUE THREAD

**Issue by DFS-90** [Hypfer/deye-microinverter-cloud-free#12]
Hi,

I forked vordenken's fork of your excellent Deye dummycloud (thank you!) in order to make it accessible for HomeAssistant as an add-on repository.

I created "repository.yaml", "dummycloud/build.yaml", "dummycloud/config.yaml" and edited "dummycloud/Dockerfile" in order to be able to add your dummycloud as a HomeAssistant Supervisor add-on.
Please find all mentioned files [here](https://github.com/DFS-90/deye-microinverter-cloud-free).

As I am not able to program anything myself or to maintain this repository further, I wanted to ask if you're interested in adding those files to your "original" dummycloud repository.

Thanks for your and vordenken's great work and best regards,
David

**Comment by Hypfer** [comment]
While this sounds like a good idea at first glance, if you think about it for a bit, it really isn't. This is because the repository contains what I did, what I know and how I use this software.

I've never used HASS OS or HA Supervised. I have absolutely no clue how those systems work. While I could add these files to the repo, that wouldn't be of much help since they might work or might not work and I just wouldn't know because I don't use and have never used the supervisor stuff.

I'd argue that it would actually be **worse** to have them even though I have no clue how/if they work, because if someone sees them, they'd expect that the repository is tested to work in that configuration and thus be angry/disappointed to find out that that's not the case.
