### ISSUE TITLE
dummycloud not working with latest version of firmware

### ISSUE THREAD

**Issue by apphancer** [Hypfer/deye-microinverter-cloud-free#20]
I have a M80G3 and it's firmware got updated OTA not long ago. The current firmware version on this device is MW3_SSL_5408_1.0B

In the README.md file of this repo, it is stated that:

> Deye has started rolling out firmware updates for the logger that block both ModbusTCP access and prevent the mock cloud from working due to the introduction of TLS. Fortunately, for now it seems that newly bought inverters still come with older logger firmwares that work offline. Also equally fortunately, it seems that downgrading the firmware is possible as well.

However, there is another project out there that seems to work https://github.com/jmccrohan/pysolarmanv5 (I haven't been able to play around it with it yet). I was wondering if there was a way around for the dummycloud project to be able to work around the issues with the introduction of TLS.

Unfortunately, I have not been able to downgrade my firmware to an older version. I have tried with these bin files here https://github.com/dasrecht/deye-firmware/tree/main/0_D0002_18 but the firmware change does not apply.

**Comment by Hypfer** [comment]
Well it is highly unlikely that you'll receive an answer by anyone but yourself, because the last thing people with a working setup will do is update their inverters, bricking them in the process and then solve what is effectively just your own problem.

If you figure out a solution, feel free to let the internet know by opening a new issue.
For now however, there is nothing that can be done here from any side other than yours

**Comment by apphancer** [comment]
No worries. I have a different approach to get the data I need, and it works. I just wanted to check the plans for the dummycloud project, and your answer is pretty clear about the direction of things. Cheers.
